# Generated by Django 2.2.3 on 2019-08-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pizza_image')),
                ('price', models.IntegerField(default=0)),
                ('pizza_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaShopApp.PizzaShop')),
            ],
        ),
    ]
